services:
  mikrotik-dns-switcher:
    container_name: mikrotik-dns-switcher
    build: .
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
